### ISSUE TITLE
UI Shattering and Shrinking After Image Selection: High Priority

### ISSUE THREAD

**Issue by NamrataPb** [PiyushPb/Vichar-Twitter-inspired-application#9]
## Subject: Issue Report: UI Shattering and Shrinking After Image Selection

**Description:**

**Problem:**
Upon selecting images within the UI, the interface shatters and reduces in size drastically, causing inconvenience and hindering user interaction.

**Reproduction Steps:**
1. Launch the application.
2. Navigate to the create post button.
3. Select multiple images or perform any action that involves image selection.
4. Observe the UI shrinking and shattering unexpectedly.

**Expected Behavior:**
After selecting images, the UI should maintain its structure and size, providing a smooth and seamless user experience.

**Actual Behavior:**
The UI shatters and becomes significantly smaller, impacting usability and causing frustration among users.

**Additional Information:**
- **Environment:** Windows(Chrome, Firefox, Brave), Android/iOS/tablet(Chrome, Firefox, Brave).
- **Console Errors:** None.
- **Frequency:** Problem occurs consistently.
- **Screenshots/Recordings:** 
![ss2](https://github.com/PiyushPb/Vichar-Twitter-inspired-application/assets/82031104/14f581dc-e046-4d4a-a683-1647d43b99ed)
![ss1](https://github.com/PiyushPb/Vichar-Twitter-inspired-application/assets/82031104/0ec7ffab-7c82-4301-9c64-4815ab199923)

**Priority:**
## High

Submitted By , @NamrataPb 
Thank you.

**Comment by PiyushPb** [comment]
![image](https://github.com/PiyushPb/Vichar-Twitter-inspired-application/assets/82027371/66cc1db0-e6cd-41b8-a5e0-dc2973b25af8)
![image](https://github.com/PiyushPb/Vichar-Twitter-inspired-application/assets/82027371/d53e340b-73f9-46fb-b2f2-4511961f23f2)

The bug has been fixed!
